language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
env:
  - CONFIG="pip install pytest==2.3 pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest==2.3 --use-mirrors"
  - CONFIG="pip install pytest==2.3.1 pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest==2.3.1 --use-mirrors"
  - CONFIG="pip install pytest==2.3.2 pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest==2.3.2 --use-mirrors"
  - CONFIG="pip install pytest==2.3.3 pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest==2.3.3 --use-mirrors"
  - CONFIG="pip install pytest==2.3.4 pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest==2.3.4 --use-mirrors"
  - CONFIG-x="pip install pytest pytest-xdist --use-mirrors"
  - CONFIG="pip install pytest --use-mirrors"

install: 
  - $CONFIG
  - "python setup.py install"
# command to run tests
script: "py.test ."